
#ifndef REGISTER_LIST_H
#define REGISTER_LIST_H

#include <Arduino.h>

/* Register Address */
#define FUNC_CFG_ACCESS          0x01
#define PIN_CTRL                 0x02
#define IF_CFG                   0x03
#define ODR_TRIG_CFG             0x06
#define FIFO_CTRL1               0x07
#define FIFO_CTRL2               0x08
#define FIFO_CTRL3               0x09
#define FIFO_CTRL4               0x0A
#define COUNTER_BDR_REG1         0x0B
#define COUNTER_BDR_REG2         0x0C
#define INT1_CTRL                0x0D
#define INT2_CTRL                0x0E
#define WHO_AM_I                 0x0F
#define CTRL1                    0x10
#define CTRL2                    0x11
#define CTRL3                    0x12
#define CTRL4                    0x13
#define CTRL5                    0x14
#define CTRL6                    0x15
#define CTRL7                    0x16
#define CTRL8                    0x17
#define CTRL9                    0x18
#define CTRL10                   0x19
#define CTRL_STATUS              0x1A
#define FIFO_STATUS1             0x1B
#define FIFO_STATUS2             0x1C
#define ALL_INT_SRC              0x1D
#define STATUS_REG               0x1E
#define OUT_TEMP_L               0x20
#define OUT_TEMP_H               0x21
#define OUTX_L_G                 0x22
#define OUTX_H_G                 0x23
#define OUTY_L_G                 0x24
#define OUTY_H_G                 0x25
#define OUTZ_L_G                 0x26
#define OUTZ_H_G                 0x27
#define OUTX_L_A                 0x28
#define OUTX_H_A                 0x29
#define OUTY_L_A                 0x2A
#define OUTY_H_A                 0x2B
#define OUTZ_L_A                 0x2C
#define OUTZ_H_A                 0x2D
#define UI_OUTX_L_G_OIS_EIS      0x2E
#define UI_OUTX_H_G_OIS_EIS      0x2F
#define UI_OUTY_L_G_OIS_EIS      0x30
#define UI_OUTY_H_G_OIS_EIS      0x31
#define UI_OUTZ_L_G_OIS_EIS      0x32
#define UI_OUTZ_H_G_OIS_EIS      0x33
#define UI_OUTX_L_A_OIS_DualC    0x34
#define UI_OUTX_H_A_OIS_DualC    0x35
#define UI_OUTY_L_A_OIS_DualC    0x36
#define UI_OUTY_H_A_OIS_DualC    0x37
#define UI_OUTZ_L_A_OIS_DualC    0x38
#define UI_OUTZ_H_A_OIS_DualC    0x39
#define AH_QVAR_OUT_L            0x3A
#define AH_QVAR_OUT_H            0x3B
#define TIMESTAMP0               0x40
#define TIMESTAMP1               0x41
#define TIMESTAMP2               0x42
#define TIMESTAMP3               0x43
#define UI_STATUS_REG_OIS        0x44
#define WAKE_UP_SRC              0x45
#define TAP_SRC                  0x46
#define D6D_SRC                  0x47
#define STATUS_MASTER_MAINPAGE   0x48
#define EMB_FUNC_STATUS_MAINPAGE 0x49
#define FSM_STATUS_MAINPAGE      0x4A
#define MLC_STATUS_MAINPAGE      0x4B
#define INTERNAL_FREQ_FINE       0x4F
#define FUNCTIONS_ENABLE         0x50
#define DEN                      0x51
#define INACTIVITY_DUR           0x54
#define INACTIVITY_THS           0x55
#define TAP_CFG0                 0x56
#define TAP_CFG1                 0x57
#define TAP_CFG2                 0x58
#define TAP_THS_6D               0x59
#define TAP_DUR                  0x5A
#define WAKE_UP_THS              0x5B
#define WAKE_UP_DUR              0x5C
#define FREE_FALL                0x5D
#define MD1_CFG                  0x5E
#define MD2_CFG                  0x5F
#define HAODR_CFG                0x62
#define EMB_FUNC_CFG             0x63
#define UI_HANDSHAKE_CTRL        0x64
#define UI_SPI2_SHARED_0         0x65
#define UI_SPI2_SHARED_1         0x66
#define UI_SPI2_SHARED_2         0x67
#define UI_SPI2_SHARED_3         0x68
#define UI_SPI2_SHARED_4         0x69
#define UI_SPI2_SHARED_5         0x6A
#define CTRL_EIS                 0x6B
#define UI_INT_OIS               0x6F
#define UI_CTRL1_OIS             0x70
#define UI_CTRL2_OIS             0x71
#define UI_CTRL3_OIS             0x72
#define X_OFS_USR                0x73
#define Y_OFS_USR                0x74
#define Z_OFS_USR                0x75
#define FIFO_DATA_OUT_TAG        0x78
#define FIFO_DATA_OUT_X_L        0x79
#define FIFO_DATA_OUT_X_H        0x7A
#define FIFO_DATA_OUT_Y_L        0x7B
#define FIFO_DATA_OUT_Y_H        0x7C
#define FIFO_DATA_OUT_Z_L        0x7D
#define FIFO_DATA_OUT_Z_H        0x7E

#endif